---
# Source: atlantis/templates/secret-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: atlantis-webhook
  namespace: atlantis
  labels:
    app: atlantis
    chart: atlantis-5.28.0
    release: atlantis
    heritage: Helm
data:
