---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-runners
resources:
  - namespace.yaml
  - sources.yaml
  - serviceaccount-eso.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - serviceaccount-arc.yaml
  - role.yaml
  - rolebinding.yaml
  - release.yaml
