apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-host-path.yaml
  - disallow-privilege-escalation.yaml
  - disallow-privileged-containers.yaml
  - restrict-capabilities.yaml
