---
# Source: kyverno/templates/hooks/pre-delete-scale-to-zero.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kyverno-scale-to-zero
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "90"
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: kyverno-admission-controller
      automountServiceAccountToken: true
      restartPolicy: Never
      containers:
        - name: kubectl
          image: "registry.k8s.io/kubectl:v1.34.3"
          imagePullPolicy:
          command:
            - kubectl
            - scale
            - -n
            - kyverno
            - deployment
            - -l
            - app.kubernetes.io/part-of=kyverno
            - --replicas=0
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
