---
# Source: kyverno/templates/hooks/post-upgrade-migrate-resources.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kyverno-migrate-resources
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
  annotations:
    helm.sh/hook: post-upgrade
    # helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "200"
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: kyverno-migrate-resources
      automountServiceAccountToken: true
      restartPolicy: Never
      containers:
        - name: kubectl
          image: "reg.kyverno.io/kyverno/kyverno-cli:v1.17.1"
          imagePullPolicy: IfNotPresent
          args:
            - migrate
            - --resource
            - cleanuppolicies.kyverno.io
            - --resource
            - clustercleanuppolicies.kyverno.io
            - --resource
            - clusterpolicies.kyverno.io
            - --resource
            - globalcontextentries.kyverno.io
            - --resource
            - policies.kyverno.io
            - --resource
            - policyexceptions.kyverno.io
            - --resource
            - updaterequests.kyverno.io
            - --resource
            - deletingpolicies.policies.kyverno.io
            - --resource
            - generatingpolicies.policies.kyverno.io
            - --resource
            - imagevalidatingpolicies.policies.kyverno.io
            - --resource
            - mutatingpolicies.policies.kyverno.io
            - --resource
            - namespaceddeletingpolicies.policies.kyverno.io
            - --resource
            - namespacedgeneratingpolicies.policies.kyverno.io
            - --resource
            - namespacedimagevalidatingpolicies.policies.kyverno.io
            - --resource
            - namespacedmutatingpolicies.policies.kyverno.io
            - --resource
            - namespacedvalidatingpolicies.policies.kyverno.io
            - --resource
            - policyexceptions.policies.kyverno.io
            - --resource
            - validatingpolicies.policies.kyverno.io
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
