---
# Source: kyverno/templates/cleanup-controller/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-cleanup-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
automountServiceAccountToken: false
