---
# Source: kyverno/templates/reports-controller/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-reports-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/component: reports-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
automountServiceAccountToken: false
