---
# Source: kyverno/templates/hooks/post-upgrade-migrate-resources.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-migrate-resources
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "100"
automountServiceAccountToken: false
