---
# Source: kyverno/templates/background-controller/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-background-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
automountServiceAccountToken: false
