apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis
resources:
  - namespace.yaml
  - source.yaml
  - secretstore-ssm.yaml
  - externalsecret-1password-auth.yaml
  - externalsecret-basic-auth.yaml
  - externalsecret-github-auth.yaml
  - secretstore-1password.yaml
  - externalsecret-atlantis-environment.yaml
  - release.yaml
