apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis
resources:
  - namespace.yaml
  - secretstore-ssm.yaml
  - secretstore-1password.yaml
  - externalsecret-1password-connect.yaml
  - externalsecret-1password.yaml
  - externalsecret-ssm.yaml
  - release.yaml
