---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU82WEFzTUtkVVJhUkRLSjczczU1Vmt3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE16VXdNREphRncwek5qQXlNVGd4TXpVd01ESmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNoL1ZXemJDWmRab3o3NHJzZHlUeDFPeUN0clBqSEhDdjZ4SWJUclBYRTlZWHYxbXZabkZoRworRTVtRzBSN25BeTEyNWFSQ0dkVW1GankvbWtJSHdwUXozV2Z5bUQ3VjdOcmw3aWd6R1JzMzgwdUNORnpFWnptCi9lSTBpVnVVcml3QmxkTGt4VWdqUFdodnR4T2pkcEc4eU14S3hPREtnT3pBbWVkdHIzTFd6YkNpMnh6YVpDL1gKSGFQWWV1eGs1MFA5VmxCOTk2M3BHeU9rd3M1LzhneVFITWZXYXI4OHlZcDNsM2FaK0tHZUZlbmZ0YkxaS2RqMApRQmFhWFQvemZCOFhiUjBHU1owRHJNOUVCUmtKR0NYOUVjVzBpTkoyeG5KdUdheUpjRFZLMmVrRTRzTmJkMWhlCmZjQlIwUnhhNG14OG1QKy91M1RIZVhjU1VVRUhsaTNoQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVV3JmUmtaV1JubFJTL0x0dXBkWG9HWlF2c2FRd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBR0dEWk4zb256QjJEbVNPazdoTUNTOUROc09kSkFIUmFzQTJyb2JQMHF0QkRaQit6TVFYZVI1Nm92encKbmVOdGF6QWVNRkFubXBnTEU0WjVlSktnWC80RW5YNnVHYkV0TGx5RWxkd3E5TkUra3ZTYm1XWjJxU2RTSFEyZAp5MXI5akpURlZCYzJPZUxBOUtTWnVnamZicnVMS0NKWUNSSWc1WUVzWDlNd1hCOTMxQUExRzdadkovOUxWUmRPCklFeEhvVllZM1RKczZQeEZIUHRFOXhDQmF4RlJyNnpsYnlObEdtT21qemtaaVRKWHljYlVTaDBESXNtbTdJd1oKTVZkOE95QVZGUGNPV1FjV0VUclk3NU9uVGphQitNODdYemoydWpCRWdzUTFzdXhoUDBSTHd0SkVieGFyNC95WgpRZm1YMTBOL0pBZXRNTTBNVEh1RVhINDRGem89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-pod
    failurePolicy: Ignore
    name: mpod.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/pod-readiness-gate-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU82WEFzTUtkVVJhUkRLSjczczU1Vmt3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE16VXdNREphRncwek5qQXlNVGd4TXpVd01ESmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNoL1ZXemJDWmRab3o3NHJzZHlUeDFPeUN0clBqSEhDdjZ4SWJUclBYRTlZWHYxbXZabkZoRworRTVtRzBSN25BeTEyNWFSQ0dkVW1GankvbWtJSHdwUXozV2Z5bUQ3VjdOcmw3aWd6R1JzMzgwdUNORnpFWnptCi9lSTBpVnVVcml3QmxkTGt4VWdqUFdodnR4T2pkcEc4eU14S3hPREtnT3pBbWVkdHIzTFd6YkNpMnh6YVpDL1gKSGFQWWV1eGs1MFA5VmxCOTk2M3BHeU9rd3M1LzhneVFITWZXYXI4OHlZcDNsM2FaK0tHZUZlbmZ0YkxaS2RqMApRQmFhWFQvemZCOFhiUjBHU1owRHJNOUVCUmtKR0NYOUVjVzBpTkoyeG5KdUdheUpjRFZLMmVrRTRzTmJkMWhlCmZjQlIwUnhhNG14OG1QKy91M1RIZVhjU1VVRUhsaTNoQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVV3JmUmtaV1JubFJTL0x0dXBkWG9HWlF2c2FRd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBR0dEWk4zb256QjJEbVNPazdoTUNTOUROc09kSkFIUmFzQTJyb2JQMHF0QkRaQit6TVFYZVI1Nm92encKbmVOdGF6QWVNRkFubXBnTEU0WjVlSktnWC80RW5YNnVHYkV0TGx5RWxkd3E5TkUra3ZTYm1XWjJxU2RTSFEyZAp5MXI5akpURlZCYzJPZUxBOUtTWnVnamZicnVMS0NKWUNSSWc1WUVzWDlNd1hCOTMxQUExRzdadkovOUxWUmRPCklFeEhvVllZM1RKczZQeEZIUHRFOXhDQmF4RlJyNnpsYnlObEdtT21qemtaaVRKWHljYlVTaDBESXNtbTdJd1oKTVZkOE95QVZGUGNPV1FjV0VUclk3NU9uVGphQitNODdYemoydWpCRWdzUTFzdXhoUDBSTHd0SkVieGFyNC95WgpRZm1YMTBOL0pBZXRNTTBNVEh1RVhINDRGem89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-pod-server-id
    failurePolicy: Fail
    name: quicid.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/quic-server-id-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU82WEFzTUtkVVJhUkRLSjczczU1Vmt3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE16VXdNREphRncwek5qQXlNVGd4TXpVd01ESmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNoL1ZXemJDWmRab3o3NHJzZHlUeDFPeUN0clBqSEhDdjZ4SWJUclBYRTlZWHYxbXZabkZoRworRTVtRzBSN25BeTEyNWFSQ0dkVW1GankvbWtJSHdwUXozV2Z5bUQ3VjdOcmw3aWd6R1JzMzgwdUNORnpFWnptCi9lSTBpVnVVcml3QmxkTGt4VWdqUFdodnR4T2pkcEc4eU14S3hPREtnT3pBbWVkdHIzTFd6YkNpMnh6YVpDL1gKSGFQWWV1eGs1MFA5VmxCOTk2M3BHeU9rd3M1LzhneVFITWZXYXI4OHlZcDNsM2FaK0tHZUZlbmZ0YkxaS2RqMApRQmFhWFQvemZCOFhiUjBHU1owRHJNOUVCUmtKR0NYOUVjVzBpTkoyeG5KdUdheUpjRFZLMmVrRTRzTmJkMWhlCmZjQlIwUnhhNG14OG1QKy91M1RIZVhjU1VVRUhsaTNoQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVV3JmUmtaV1JubFJTL0x0dXBkWG9HWlF2c2FRd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBR0dEWk4zb256QjJEbVNPazdoTUNTOUROc09kSkFIUmFzQTJyb2JQMHF0QkRaQit6TVFYZVI1Nm92encKbmVOdGF6QWVNRkFubXBnTEU0WjVlSktnWC80RW5YNnVHYkV0TGx5RWxkd3E5TkUra3ZTYm1XWjJxU2RTSFEyZAp5MXI5akpURlZCYzJPZUxBOUtTWnVnamZicnVMS0NKWUNSSWc1WUVzWDlNd1hCOTMxQUExRzdadkovOUxWUmRPCklFeEhvVllZM1RKczZQeEZIUHRFOXhDQmF4RlJyNnpsYnlObEdtT21qemtaaVRKWHljYlVTaDBESXNtbTdJd1oKTVZkOE95QVZGUGNPV1FjV0VUclk3NU9uVGphQitNODdYemoydWpCRWdzUTFzdXhoUDBSTHd0SkVieGFyNC95WgpRZm1YMTBOL0pBZXRNTTBNVEh1RVhINDRGem89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-service
    failurePolicy: Fail
    name: mservice.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - services
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU82WEFzTUtkVVJhUkRLSjczczU1Vmt3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE16VXdNREphRncwek5qQXlNVGd4TXpVd01ESmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNoL1ZXemJDWmRab3o3NHJzZHlUeDFPeUN0clBqSEhDdjZ4SWJUclBYRTlZWHYxbXZabkZoRworRTVtRzBSN25BeTEyNWFSQ0dkVW1GankvbWtJSHdwUXozV2Z5bUQ3VjdOcmw3aWd6R1JzMzgwdUNORnpFWnptCi9lSTBpVnVVcml3QmxkTGt4VWdqUFdodnR4T2pkcEc4eU14S3hPREtnT3pBbWVkdHIzTFd6YkNpMnh6YVpDL1gKSGFQWWV1eGs1MFA5VmxCOTk2M3BHeU9rd3M1LzhneVFITWZXYXI4OHlZcDNsM2FaK0tHZUZlbmZ0YkxaS2RqMApRQmFhWFQvemZCOFhiUjBHU1owRHJNOUVCUmtKR0NYOUVjVzBpTkoyeG5KdUdheUpjRFZLMmVrRTRzTmJkMWhlCmZjQlIwUnhhNG14OG1QKy91M1RIZVhjU1VVRUhsaTNoQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVV3JmUmtaV1JubFJTL0x0dXBkWG9HWlF2c2FRd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBR0dEWk4zb256QjJEbVNPazdoTUNTOUROc09kSkFIUmFzQTJyb2JQMHF0QkRaQit6TVFYZVI1Nm92encKbmVOdGF6QWVNRkFubXBnTEU0WjVlSktnWC80RW5YNnVHYkV0TGx5RWxkd3E5TkUra3ZTYm1XWjJxU2RTSFEyZAp5MXI5akpURlZCYzJPZUxBOUtTWnVnamZicnVMS0NKWUNSSWc1WUVzWDlNd1hCOTMxQUExRzdadkovOUxWUmRPCklFeEhvVllZM1RKczZQeEZIUHRFOXhDQmF4RlJyNnpsYnlObEdtT21qemtaaVRKWHljYlVTaDBESXNtbTdJd1oKTVZkOE95QVZGUGNPV1FjV0VUclk3NU9uVGphQitNODdYemoydWpCRWdzUTFzdXhoUDBSTHd0SkVieGFyNC95WgpRZm1YMTBOL0pBZXRNTTBNVEh1RVhINDRGem89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-alb-target-control-namespace-v1-pod
    failurePolicy: Fail
    name: alb-target-control.namespace.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: NotIn
          values:
            - "false"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU82WEFzTUtkVVJhUkRLSjczczU1Vmt3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE16VXdNREphRncwek5qQXlNVGd4TXpVd01ESmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNoL1ZXemJDWmRab3o3NHJzZHlUeDFPeUN0clBqSEhDdjZ4SWJUclBYRTlZWHYxbXZabkZoRworRTVtRzBSN25BeTEyNWFSQ0dkVW1GankvbWtJSHdwUXozV2Z5bUQ3VjdOcmw3aWd6R1JzMzgwdUNORnpFWnptCi9lSTBpVnVVcml3QmxkTGt4VWdqUFdodnR4T2pkcEc4eU14S3hPREtnT3pBbWVkdHIzTFd6YkNpMnh6YVpDL1gKSGFQWWV1eGs1MFA5VmxCOTk2M3BHeU9rd3M1LzhneVFITWZXYXI4OHlZcDNsM2FaK0tHZUZlbmZ0YkxaS2RqMApRQmFhWFQvemZCOFhiUjBHU1owRHJNOUVCUmtKR0NYOUVjVzBpTkoyeG5KdUdheUpjRFZLMmVrRTRzTmJkMWhlCmZjQlIwUnhhNG14OG1QKy91M1RIZVhjU1VVRUhsaTNoQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVV3JmUmtaV1JubFJTL0x0dXBkWG9HWlF2c2FRd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBR0dEWk4zb256QjJEbVNPazdoTUNTOUROc09kSkFIUmFzQTJyb2JQMHF0QkRaQit6TVFYZVI1Nm92encKbmVOdGF6QWVNRkFubXBnTEU0WjVlSktnWC80RW5YNnVHYkV0TGx5RWxkd3E5TkUra3ZTYm1XWjJxU2RTSFEyZAp5MXI5akpURlZCYzJPZUxBOUtTWnVnamZicnVMS0NKWUNSSWc1WUVzWDlNd1hCOTMxQUExRzdadkovOUxWUmRPCklFeEhvVllZM1RKczZQeEZIUHRFOXhDQmF4RlJyNnpsYnlObEdtT21qemtaaVRKWHljYlVTaDBESXNtbTdJd1oKTVZkOE95QVZGUGNPV1FjV0VUclk3NU9uVGphQitNODdYemoydWpCRWdzUTFzdXhoUDBSTHd0SkVieGFyNC95WgpRZm1YMTBOL0pBZXRNTTBNVEh1RVhINDRGem89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-alb-target-control-object-v1-pod
    failurePolicy: Fail
    name: alb-target-control.object.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: In
          values:
            - "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU82WEFzTUtkVVJhUkRLSjczczU1Vmt3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE16VXdNREphRncwek5qQXlNVGd4TXpVd01ESmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNoL1ZXemJDWmRab3o3NHJzZHlUeDFPeUN0clBqSEhDdjZ4SWJUclBYRTlZWHYxbXZabkZoRworRTVtRzBSN25BeTEyNWFSQ0dkVW1GankvbWtJSHdwUXozV2Z5bUQ3VjdOcmw3aWd6R1JzMzgwdUNORnpFWnptCi9lSTBpVnVVcml3QmxkTGt4VWdqUFdodnR4T2pkcEc4eU14S3hPREtnT3pBbWVkdHIzTFd6YkNpMnh6YVpDL1gKSGFQWWV1eGs1MFA5VmxCOTk2M3BHeU9rd3M1LzhneVFITWZXYXI4OHlZcDNsM2FaK0tHZUZlbmZ0YkxaS2RqMApRQmFhWFQvemZCOFhiUjBHU1owRHJNOUVCUmtKR0NYOUVjVzBpTkoyeG5KdUdheUpjRFZLMmVrRTRzTmJkMWhlCmZjQlIwUnhhNG14OG1QKy91M1RIZVhjU1VVRUhsaTNoQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVV3JmUmtaV1JubFJTL0x0dXBkWG9HWlF2c2FRd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBR0dEWk4zb256QjJEbVNPazdoTUNTOUROc09kSkFIUmFzQTJyb2JQMHF0QkRaQit6TVFYZVI1Nm92encKbmVOdGF6QWVNRkFubXBnTEU0WjVlSktnWC80RW5YNnVHYkV0TGx5RWxkd3E5TkUra3ZTYm1XWjJxU2RTSFEyZAp5MXI5akpURlZCYzJPZUxBOUtTWnVnamZicnVMS0NKWUNSSWc1WUVzWDlNd1hCOTMxQUExRzdadkovOUxWUmRPCklFeEhvVllZM1RKczZQeEZIUHRFOXhDQmF4RlJyNnpsYnlObEdtT21qemtaaVRKWHljYlVTaDBESXNtbTdJd1oKTVZkOE95QVZGUGNPV1FjV0VUclk3NU9uVGphQitNODdYemoydWpCRWdzUTFzdXhoUDBSTHd0SkVieGFyNC95WgpRZm1YMTBOL0pBZXRNTTBNVEh1RVhINDRGem89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: mtargetgroupbinding.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
