---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRY3kydFBDZHBYRll4VUMvRUZBVlp2REFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNREl5TURFeU5EUXpNVm9YRFRNMk1ESXhPREV5TkRRek1Wb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXZRNjcrMTlEZ2d3Z01QbU90eTJwL1d5N1hRc2FlNndOTnVSazEyWVhNUzRmVTMvT2EwMDJ3SQpuYVZkQlhkbVFnWWRxTGx4aThTNFViNFBpYjU2UWp4RHl1MXU5aTJKdGh2eHJSaHBOaWZPYmNGakVnb3ZldVRuCkRxaDVtUG5HV1V1aUk3d2hGdnEwVWJYbzdFbXphbXhybXk0cUFDRUR0SDZMdzd6NXhpYU1KQzd1RXlEMzRMTFIKeDNka1poMzVaT1h5d3paM3I3eGFZY0NuS0FKOGFjSHM3dWNxK0dHNkpGL2VGUWg1STdMK3Q0b1JzT1JhUWQ1dApwUGxjczhOWlJoSTZONm1qNjRjNjJyL2ZsTllqTmhnUFFucEdJcFMzeS9iN1VmblhLVitIM1V0UUt5SVQxQ2FYCkZOK0FMVzRxT1U2YytMaUFiL2ZZWUk3SW5NZldwRDhDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJGUE95MW5vQWJrSUlmbmxPTVdIbHFVcEZ5YnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFYNVFnRlp2Y0NtS3YyQ2FteFVZcTd0NEhMakhFbW1wYll0WjM0Q2JaM0IyNldwczhsNW8xRDBJaFIwSmIKUC9TeFNsTzA0azI5NDlURDBMRG4yWThJN1AzV09IQzRlbHV1YzU5UklZWVlGeWR2OWhWQWg1ampKUU5Tb2NKYgpnMFBzd3h0SDNxdmdTbXNuOHFWdy83alNBMW1wRUFKNHUxRlNqMEZYZ09hVVlVWm5rbXNIaVdSbUFkQnFDdXBrCmlmcGNVQ3pGQXZGa3VGRG90UFh3TXltTkZKUy9hZWg3d1pQZU11REJXdkFPN3lrZlNXd3NiVDlJZ2VrY2tTblAKQnFQZTByamZzSkFFTjZ2UGQ3bVZ4VmxlWlB1RVp4TUkrRjBvYnpGTnRRblJmaDl6a0RsOWlxRkcrem8wVE9Gdgp4Mi9PTGpsamNLcWVjdjBwQzNHcmZadU95Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-pod
    failurePolicy: Ignore
    name: mpod.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/pod-readiness-gate-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRY3kydFBDZHBYRll4VUMvRUZBVlp2REFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNREl5TURFeU5EUXpNVm9YRFRNMk1ESXhPREV5TkRRek1Wb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXZRNjcrMTlEZ2d3Z01QbU90eTJwL1d5N1hRc2FlNndOTnVSazEyWVhNUzRmVTMvT2EwMDJ3SQpuYVZkQlhkbVFnWWRxTGx4aThTNFViNFBpYjU2UWp4RHl1MXU5aTJKdGh2eHJSaHBOaWZPYmNGakVnb3ZldVRuCkRxaDVtUG5HV1V1aUk3d2hGdnEwVWJYbzdFbXphbXhybXk0cUFDRUR0SDZMdzd6NXhpYU1KQzd1RXlEMzRMTFIKeDNka1poMzVaT1h5d3paM3I3eGFZY0NuS0FKOGFjSHM3dWNxK0dHNkpGL2VGUWg1STdMK3Q0b1JzT1JhUWQ1dApwUGxjczhOWlJoSTZONm1qNjRjNjJyL2ZsTllqTmhnUFFucEdJcFMzeS9iN1VmblhLVitIM1V0UUt5SVQxQ2FYCkZOK0FMVzRxT1U2YytMaUFiL2ZZWUk3SW5NZldwRDhDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJGUE95MW5vQWJrSUlmbmxPTVdIbHFVcEZ5YnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFYNVFnRlp2Y0NtS3YyQ2FteFVZcTd0NEhMakhFbW1wYll0WjM0Q2JaM0IyNldwczhsNW8xRDBJaFIwSmIKUC9TeFNsTzA0azI5NDlURDBMRG4yWThJN1AzV09IQzRlbHV1YzU5UklZWVlGeWR2OWhWQWg1ampKUU5Tb2NKYgpnMFBzd3h0SDNxdmdTbXNuOHFWdy83alNBMW1wRUFKNHUxRlNqMEZYZ09hVVlVWm5rbXNIaVdSbUFkQnFDdXBrCmlmcGNVQ3pGQXZGa3VGRG90UFh3TXltTkZKUy9hZWg3d1pQZU11REJXdkFPN3lrZlNXd3NiVDlJZ2VrY2tTblAKQnFQZTByamZzSkFFTjZ2UGQ3bVZ4VmxlWlB1RVp4TUkrRjBvYnpGTnRRblJmaDl6a0RsOWlxRkcrem8wVE9Gdgp4Mi9PTGpsamNLcWVjdjBwQzNHcmZadU95Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-service
    failurePolicy: Fail
    name: mservice.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - services
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRY3kydFBDZHBYRll4VUMvRUZBVlp2REFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNREl5TURFeU5EUXpNVm9YRFRNMk1ESXhPREV5TkRRek1Wb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXZRNjcrMTlEZ2d3Z01QbU90eTJwL1d5N1hRc2FlNndOTnVSazEyWVhNUzRmVTMvT2EwMDJ3SQpuYVZkQlhkbVFnWWRxTGx4aThTNFViNFBpYjU2UWp4RHl1MXU5aTJKdGh2eHJSaHBOaWZPYmNGakVnb3ZldVRuCkRxaDVtUG5HV1V1aUk3d2hGdnEwVWJYbzdFbXphbXhybXk0cUFDRUR0SDZMdzd6NXhpYU1KQzd1RXlEMzRMTFIKeDNka1poMzVaT1h5d3paM3I3eGFZY0NuS0FKOGFjSHM3dWNxK0dHNkpGL2VGUWg1STdMK3Q0b1JzT1JhUWQ1dApwUGxjczhOWlJoSTZONm1qNjRjNjJyL2ZsTllqTmhnUFFucEdJcFMzeS9iN1VmblhLVitIM1V0UUt5SVQxQ2FYCkZOK0FMVzRxT1U2YytMaUFiL2ZZWUk3SW5NZldwRDhDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJGUE95MW5vQWJrSUlmbmxPTVdIbHFVcEZ5YnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFYNVFnRlp2Y0NtS3YyQ2FteFVZcTd0NEhMakhFbW1wYll0WjM0Q2JaM0IyNldwczhsNW8xRDBJaFIwSmIKUC9TeFNsTzA0azI5NDlURDBMRG4yWThJN1AzV09IQzRlbHV1YzU5UklZWVlGeWR2OWhWQWg1ampKUU5Tb2NKYgpnMFBzd3h0SDNxdmdTbXNuOHFWdy83alNBMW1wRUFKNHUxRlNqMEZYZ09hVVlVWm5rbXNIaVdSbUFkQnFDdXBrCmlmcGNVQ3pGQXZGa3VGRG90UFh3TXltTkZKUy9hZWg3d1pQZU11REJXdkFPN3lrZlNXd3NiVDlJZ2VrY2tTblAKQnFQZTByamZzSkFFTjZ2UGQ3bVZ4VmxlWlB1RVp4TUkrRjBvYnpGTnRRblJmaDl6a0RsOWlxRkcrem8wVE9Gdgp4Mi9PTGpsamNLcWVjdjBwQzNHcmZadU95Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: mtargetgroupbinding.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
