---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUlXdU1BWTJEZC9jK3BJdXNoTnpUTW93RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE1qUXpNamhhRncwek5qQXlNVGd4TWpRek1qaGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURrWW9QUXZDNVJTTmdsNlZSaC9JODZ1UVEvSllnL08yNjUwakRqT1NJZThiTkNzRTYxbHhWVgpvcWowOXROaXVjSVVOeUxtYkRQa2p1b3pKWmpUenRnU21BbmNhQ2IvcHhVbmExRUlpSlhQSG14UGFDSTNhaGFTCnMwYXgwTnBoaUh1VWxRTmcyblZub3RxTTNLcVFOZWpzZUhJVXE1ZGMySHh4WXpHQm1odkRTcnBqZkdET29MK2sKbFdLaUNEUHFzVGlGOHRQRnl3cG9XTHBHcGlHMG4rT2FUNEdBZGdCQ3pBZVVKTnNUenFadGdGRGdDQWZVWXBEUwpoait5YUdqd1EwdW5xNG1pS2trdWY0dHJNZ3hLUytMRDZ1SGp0bFRoSE8rUXp0dUt2ai9mUmV3a3R2emE0MlRrCmNTOUt0c3NrUjcvL0VzM1BKRDJpQ1BzWDRwL2pKdGlsQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVRkRGYzNDTFo1YnRIRVFZKy9OeFRyakIwTUwwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBS25SWnpDL3VSMWJTSlVoSmpWWVA4ZmhFNlFoV0c1cWJkNThQVzVicTlrNmRKeGdYeTNPRUluQ2gwWDIKSlU4dnkxQ1FUL0twM3Z1RVlsbjhQTHRPY1pTVU4vbEtqNHVQalA5M0xqTEhPSFJIV3pIUzJFZnVVTDNiS0ZkMgp0alZBVzU4Y2ppN1RibTZtMys4bkNZTkhrbUpmM1NEZTRhZ1BJbFNHNEtHM3VQdVBEcHcvbFU0eDVUYUJyYVdTCi9URGJ4ZXFUZXFqakpmRXJhZlprZ2s4UG9LUXRUY3ljYng0OUpFdTZhbmZzSGc4d1ltb3hQWUZjQTN3ZnhhL0kKaFJtSUVpMzVlWi9CZ21Ma1c2cFRZUmJjcUM2RFpXK3RSR0g2dDd1enhVRW9xSG1xb0lUZ1V3bnRmVU54N1JVYwpPVmZVSWozRFV5akFudER1bys0c0JSbllielU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-pod
    failurePolicy: Ignore
    name: mpod.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/pod-readiness-gate-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUlXdU1BWTJEZC9jK3BJdXNoTnpUTW93RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE1qUXpNamhhRncwek5qQXlNVGd4TWpRek1qaGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURrWW9QUXZDNVJTTmdsNlZSaC9JODZ1UVEvSllnL08yNjUwakRqT1NJZThiTkNzRTYxbHhWVgpvcWowOXROaXVjSVVOeUxtYkRQa2p1b3pKWmpUenRnU21BbmNhQ2IvcHhVbmExRUlpSlhQSG14UGFDSTNhaGFTCnMwYXgwTnBoaUh1VWxRTmcyblZub3RxTTNLcVFOZWpzZUhJVXE1ZGMySHh4WXpHQm1odkRTcnBqZkdET29MK2sKbFdLaUNEUHFzVGlGOHRQRnl3cG9XTHBHcGlHMG4rT2FUNEdBZGdCQ3pBZVVKTnNUenFadGdGRGdDQWZVWXBEUwpoait5YUdqd1EwdW5xNG1pS2trdWY0dHJNZ3hLUytMRDZ1SGp0bFRoSE8rUXp0dUt2ai9mUmV3a3R2emE0MlRrCmNTOUt0c3NrUjcvL0VzM1BKRDJpQ1BzWDRwL2pKdGlsQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVRkRGYzNDTFo1YnRIRVFZKy9OeFRyakIwTUwwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBS25SWnpDL3VSMWJTSlVoSmpWWVA4ZmhFNlFoV0c1cWJkNThQVzVicTlrNmRKeGdYeTNPRUluQ2gwWDIKSlU4dnkxQ1FUL0twM3Z1RVlsbjhQTHRPY1pTVU4vbEtqNHVQalA5M0xqTEhPSFJIV3pIUzJFZnVVTDNiS0ZkMgp0alZBVzU4Y2ppN1RibTZtMys4bkNZTkhrbUpmM1NEZTRhZ1BJbFNHNEtHM3VQdVBEcHcvbFU0eDVUYUJyYVdTCi9URGJ4ZXFUZXFqakpmRXJhZlprZ2s4UG9LUXRUY3ljYng0OUpFdTZhbmZzSGc4d1ltb3hQWUZjQTN3ZnhhL0kKaFJtSUVpMzVlWi9CZ21Ma1c2cFRZUmJjcUM2RFpXK3RSR0g2dDd1enhVRW9xSG1xb0lUZ1V3bnRmVU54N1JVYwpPVmZVSWozRFV5akFudER1bys0c0JSbllielU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-service
    failurePolicy: Fail
    name: mservice.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - services
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUlXdU1BWTJEZC9jK3BJdXNoTnpUTW93RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE1qUXpNamhhRncwek5qQXlNVGd4TWpRek1qaGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURrWW9QUXZDNVJTTmdsNlZSaC9JODZ1UVEvSllnL08yNjUwakRqT1NJZThiTkNzRTYxbHhWVgpvcWowOXROaXVjSVVOeUxtYkRQa2p1b3pKWmpUenRnU21BbmNhQ2IvcHhVbmExRUlpSlhQSG14UGFDSTNhaGFTCnMwYXgwTnBoaUh1VWxRTmcyblZub3RxTTNLcVFOZWpzZUhJVXE1ZGMySHh4WXpHQm1odkRTcnBqZkdET29MK2sKbFdLaUNEUHFzVGlGOHRQRnl3cG9XTHBHcGlHMG4rT2FUNEdBZGdCQ3pBZVVKTnNUenFadGdGRGdDQWZVWXBEUwpoait5YUdqd1EwdW5xNG1pS2trdWY0dHJNZ3hLUytMRDZ1SGp0bFRoSE8rUXp0dUt2ai9mUmV3a3R2emE0MlRrCmNTOUt0c3NrUjcvL0VzM1BKRDJpQ1BzWDRwL2pKdGlsQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVRkRGYzNDTFo1YnRIRVFZKy9OeFRyakIwTUwwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBS25SWnpDL3VSMWJTSlVoSmpWWVA4ZmhFNlFoV0c1cWJkNThQVzVicTlrNmRKeGdYeTNPRUluQ2gwWDIKSlU4dnkxQ1FUL0twM3Z1RVlsbjhQTHRPY1pTVU4vbEtqNHVQalA5M0xqTEhPSFJIV3pIUzJFZnVVTDNiS0ZkMgp0alZBVzU4Y2ppN1RibTZtMys4bkNZTkhrbUpmM1NEZTRhZ1BJbFNHNEtHM3VQdVBEcHcvbFU0eDVUYUJyYVdTCi9URGJ4ZXFUZXFqakpmRXJhZlprZ2s4UG9LUXRUY3ljYng0OUpFdTZhbmZzSGc4d1ltb3hQWUZjQTN3ZnhhL0kKaFJtSUVpMzVlWi9CZ21Ma1c2cFRZUmJjcUM2RFpXK3RSR0g2dDd1enhVRW9xSG1xb0lUZ1V3bnRmVU54N1JVYwpPVmZVSWozRFV5akFudER1bys0c0JSbllielU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: mtargetgroupbinding.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
