---
# Source: aws-load-balancer-controller/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-lb-controller-aws-load-balancer-controller-leader-election-rolebinding
  namespace: aws-lb-controller
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-lb-controller-aws-load-balancer-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: aws-lb-controller
    namespace: aws-lb-controller
