---
# Source: aws-load-balancer-controller/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-lb-controller-aws-load-balancer-controller-leader-election-role
  namespace: aws-lb-controller
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [create]
  - apiGroups: [""]
    resources: [configmaps]
    resourceNames: [aws-load-balancer-controller-leader]
    verbs: [get, patch, update]
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    resourceNames:
      - aws-load-balancer-controller-leader
    verbs:
      - get
      - update
      - patch
