---
# Source: aws-load-balancer-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-lb-controller
  namespace: aws-lb-controller
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
  annotations:
    eks.amazonaws.com/role-arn: ${flux_aws_lb_controller_role_arn}
automountServiceAccountToken: true
