---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpHVExjT3ptNmhWdS94VVpWZ0owdW93RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE1qUXpNekZhRncwek5qQXlNVGd4TWpRek16RmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUREbzRZcmMxM0pydExJQUNXTm1NVnRJK2RjMzdDdXc5a0p5eU1yM0YwS1NJTWVNQzlQNk11WApBY2hGbHEvTlo2Y3VPY1BjaDZ2VWVVd09rYWoxcHpvdnNtU1J3eDNpQTVRY0ROYlFiUWFIZVVuUzNHb1RBRmRzCnRJdjFOaTc4SlZhT2kxbDJIWTRvdFdiZkpTQ0x0a2F6N2hqQzJrMkRBUjhJSU1SRm8yamhRNXVOUk9IZTlkS1YKYUZMeVFYVE5FMnAvVVB5M3l2SldlYWw3QWpTVnNoQ2Nyb0MvMjhtMUxXK29wOXRUNzJ4U2t2T2h1UVUrZkVxYwo2QnRWbjJRREJWRXFvQjdBQ05IQzF1OWVpMXNialZpeit0MUUvR2VPZDE0NnRUcHdYTmtiWVNSdysvakFJVXJQCkRjNWoxakdrQ0pjT1g5TlFWMmorRk1XeGRBM1A2V0JuQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVQ0tGMEFSRG0rQjZHekVzWGpBYzZQSkFPSFdzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSjJ4cVR1UktnN3gyL1EvYmVGeWhkNUJGOTBUSHBnVCs2M3NuelE4NVBtdHp2MlZuQUM1RGEzQk0vRTQKZFF0MmxkNWhRY282OHo1Z0F6cGQ5SGJTSTc5SmRGOFdvZDUvdk9MaU5vQk8wSG40dUtjZEFVUVZ4TktoYm13WQpuelRYekhMNFozZ3l4V0hmbi93NnJTWU0vL3p0eGh0SSt1SlJsc2lYOFFGR0JHUFR4VFA3MFZUNWltN1E0Ky9qCmh3YWxEUWRvSFUxR1hQZjcyZHNrMFdpQ0Q0UWFSbUE2NHZrUlRaQVJyZUIwODIwTU1IMEdUeElKR0R3ZUs2VEsKK0Q5ajd1Q1JzWEZGWmNTTUhwZWVBNjNqS0hQZXlGSDBnc3FUbWVUSVpUT3BraFhxWGRwOWxtcHFvVzhJZzBsSQp2Wkp3ZTMxNGNSdDJVZXF4WDZNOEN4UjJkdXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
    failurePolicy: Fail
    name: vingressclassparams.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingressclassparams
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpHVExjT3ptNmhWdS94VVpWZ0owdW93RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE1qUXpNekZhRncwek5qQXlNVGd4TWpRek16RmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUREbzRZcmMxM0pydExJQUNXTm1NVnRJK2RjMzdDdXc5a0p5eU1yM0YwS1NJTWVNQzlQNk11WApBY2hGbHEvTlo2Y3VPY1BjaDZ2VWVVd09rYWoxcHpvdnNtU1J3eDNpQTVRY0ROYlFiUWFIZVVuUzNHb1RBRmRzCnRJdjFOaTc4SlZhT2kxbDJIWTRvdFdiZkpTQ0x0a2F6N2hqQzJrMkRBUjhJSU1SRm8yamhRNXVOUk9IZTlkS1YKYUZMeVFYVE5FMnAvVVB5M3l2SldlYWw3QWpTVnNoQ2Nyb0MvMjhtMUxXK29wOXRUNzJ4U2t2T2h1UVUrZkVxYwo2QnRWbjJRREJWRXFvQjdBQ05IQzF1OWVpMXNialZpeit0MUUvR2VPZDE0NnRUcHdYTmtiWVNSdysvakFJVXJQCkRjNWoxakdrQ0pjT1g5TlFWMmorRk1XeGRBM1A2V0JuQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVQ0tGMEFSRG0rQjZHekVzWGpBYzZQSkFPSFdzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSjJ4cVR1UktnN3gyL1EvYmVGeWhkNUJGOTBUSHBnVCs2M3NuelE4NVBtdHp2MlZuQUM1RGEzQk0vRTQKZFF0MmxkNWhRY282OHo1Z0F6cGQ5SGJTSTc5SmRGOFdvZDUvdk9MaU5vQk8wSG40dUtjZEFVUVZ4TktoYm13WQpuelRYekhMNFozZ3l4V0hmbi93NnJTWU0vL3p0eGh0SSt1SlJsc2lYOFFGR0JHUFR4VFA3MFZUNWltN1E0Ky9qCmh3YWxEUWRvSFUxR1hQZjcyZHNrMFdpQ0Q0UWFSbUE2NHZrUlRaQVJyZUIwODIwTU1IMEdUeElKR0R3ZUs2VEsKK0Q5ajd1Q1JzWEZGWmNTTUhwZWVBNjNqS0hQZXlGSDBnc3FUbWVUSVpUT3BraFhxWGRwOWxtcHFvVzhJZzBsSQp2Wkp3ZTMxNGNSdDJVZXF4WDZNOEN4UjJkdXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: vtargetgroupbinding.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpHVExjT3ptNmhWdS94VVpWZ0owdW93RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF5TWpBeE1qUXpNekZhRncwek5qQXlNVGd4TWpRek16RmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUREbzRZcmMxM0pydExJQUNXTm1NVnRJK2RjMzdDdXc5a0p5eU1yM0YwS1NJTWVNQzlQNk11WApBY2hGbHEvTlo2Y3VPY1BjaDZ2VWVVd09rYWoxcHpvdnNtU1J3eDNpQTVRY0ROYlFiUWFIZVVuUzNHb1RBRmRzCnRJdjFOaTc4SlZhT2kxbDJIWTRvdFdiZkpTQ0x0a2F6N2hqQzJrMkRBUjhJSU1SRm8yamhRNXVOUk9IZTlkS1YKYUZMeVFYVE5FMnAvVVB5M3l2SldlYWw3QWpTVnNoQ2Nyb0MvMjhtMUxXK29wOXRUNzJ4U2t2T2h1UVUrZkVxYwo2QnRWbjJRREJWRXFvQjdBQ05IQzF1OWVpMXNialZpeit0MUUvR2VPZDE0NnRUcHdYTmtiWVNSdysvakFJVXJQCkRjNWoxakdrQ0pjT1g5TlFWMmorRk1XeGRBM1A2V0JuQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVQ0tGMEFSRG0rQjZHekVzWGpBYzZQSkFPSFdzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSjJ4cVR1UktnN3gyL1EvYmVGeWhkNUJGOTBUSHBnVCs2M3NuelE4NVBtdHp2MlZuQUM1RGEzQk0vRTQKZFF0MmxkNWhRY282OHo1Z0F6cGQ5SGJTSTc5SmRGOFdvZDUvdk9MaU5vQk8wSG40dUtjZEFVUVZ4TktoYm13WQpuelRYekhMNFozZ3l4V0hmbi93NnJTWU0vL3p0eGh0SSt1SlJsc2lYOFFGR0JHUFR4VFA3MFZUNWltN1E0Ky9qCmh3YWxEUWRvSFUxR1hQZjcyZHNrMFdpQ0Q0UWFSbUE2NHZrUlRaQVJyZUIwODIwTU1IMEdUeElKR0R3ZUs2VEsKK0Q5ajd1Q1JzWEZGWmNTTUhwZWVBNjNqS0hQZXlGSDBnc3FUbWVUSVpUT3BraFhxWGRwOWxtcHFvVzhJZzBsSQp2Wkp3ZTMxNGNSdDJVZXF4WDZNOEN4UjJkdXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /validate-networking-v1-ingress
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: vingress.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    sideEffects: None
