---
# Source: connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: null
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: 1password-connect
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: onepassword-connect
  ports:
    - port: 8081
      name: connect-sync
    - port: 8080
      name: connect-api
